# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Social Network" conversionOrder="2147483647" description="Membership of a social network" displayName="Affiliation" displayNamePlural="Affiliations" id="maltego.Affiliation" largeIconResource="Facebook" smallIconResource="Facebook" visible="true">
	   <Properties displayValue="person.name" value="person.name">
	      <Fields>
	         <Field description="" displayName="Name" hidden="false" name="person.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Mark Zuckerberg</SampleValue>
	         </Field>
	         <Field description="" displayName="Network" hidden="false" name="affiliation.network" nullable="true" readonly="true" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="UID" hidden="false" name="affiliation.uid" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Profile URL" hidden="false" name="affiliation.profile-url" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Affiliation(entities.MaltegoEntity):
	"""
	Membership of a social network
	"""

	id = 'maltego.Affiliation'
	displayName = 'Affiliation'
	displayNamePlural = 'Affiliations'

	person_name = None # string person.name
	affiliation_network = None # string affiliation.network
	affiliation_uid = None # string affiliation.uid
	affiliation_profile_url = None # string affiliation.profile-url

	_fields = {
		'person_name': {'name': 'person.name', 'type': 'string', 'nullable': 'true'},
		'affiliation_network': {'name': 'affiliation.network', 'type': 'string', 'nullable': 'true'},
		'affiliation_uid': {'name': 'affiliation.uid', 'type': 'string', 'nullable': 'true'},
		'affiliation_profile_url': {'name': 'affiliation.profile-url', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, person_name=None, affiliation_network=None, affiliation_uid=None, affiliation_profile_url=None, **kwargs):
		super().__init__(value, **kwargs)
		self.person_name = person_name
		self.affiliation_network = affiliation_network
		self.affiliation_uid = affiliation_uid
		self.affiliation_profile_url = affiliation_profile_url

entities.entity_map[Affiliation.id] = Affiliation
