# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Personal" conversionOrder="2147483647" description="An alias for a person" displayName="Alias" displayNamePlural="Aliases" id="maltego.Alias" largeIconResource="Alias" smallIconResource="Alias" visible="true">
	   <Properties displayValue="alias" value="alias">
	      <Fields>
	         <Field description="An Alias for a person" displayName="Alias" hidden="false" name="alias" nullable="true" readonly="false" type="string">
	            <SampleValue>Mr. T</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Alias(entities.MaltegoEntity):
	"""
	An alias for a person
	"""

	id = 'maltego.Alias'
	displayName = 'Alias'
	displayNamePlural = 'Aliases'

	alias = None # string alias

	_fields = {
		'alias': {'name': 'alias', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, alias=None, **kwargs):
		super().__init__(value, **kwargs)
		self.alias = alias

entities.entity_map[Alias.id] = Alias
