# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="2147483647" description="An internet Autonomous System (AS)" displayName="AS" displayNamePlural="ASs" id="maltego.AS" largeIconResource="AS" smallIconResource="AS" visible="true">
	   <Properties displayValue="as.number" value="as.number">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="AS Number" hidden="false" name="as.number" nullable="true" readonly="false" type="string">
	            <SampleValue>188</SampleValue>
	         </Field>
	         <Field description="" hidden="false" name="Before" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" hidden="false" name="After" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Include Media Type" hidden="false" name="includeMediaType" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Exclude Media Type" hidden="false" name="excludeMediaType" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class AS(entities.MaltegoEntity):
	"""
	An internet Autonomous System (AS)
	"""

	id = 'maltego.AS'
	displayName = 'AS'
	displayNamePlural = 'ASs'

	as_number = None # string as.number
	before = None # string Before
	after = None # string After
	includemediatype = None # string includeMediaType
	excludemediatype = None # string excludeMediaType

	_fields = {
		'as_number': {'name': 'as.number', 'type': 'string', 'nullable': 'true'},
		'before': {'name': 'Before', 'type': 'string', 'nullable': 'true'},
		'after': {'name': 'After', 'type': 'string', 'nullable': 'true'},
		'includemediatype': {'name': 'includeMediaType', 'type': 'string', 'nullable': 'true'},
		'excludemediatype': {'name': 'excludeMediaType', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, as_number=None, before=None, after=None, includemediatype=None, excludemediatype=None, **kwargs):
		super().__init__(value, **kwargs)
		self.as_number = as_number
		self.before = before
		self.after = after
		self.includemediatype = includemediatype
		self.excludemediatype = excludemediatype

entities.entity_map[AS.id] = AS
