# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="AV Detection" displayName="AV Detection" displayNamePlural="AV Detections" id="maltego.Avdetection" largeIconResource="Quarantine" smallIconResource="Quarantine" visible="true">
	   <Properties displayValue="properties.avdetection" value="properties.avdetection">
	      <Fields>
	         <Field description="" displayName="AV Detection" hidden="false" name="properties.avdetection" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Avdetection(entities.MaltegoEntity):
	"""
	AV Detection
	"""

	id = 'maltego.Avdetection'
	displayName = 'AV Detection'
	displayNamePlural = 'AV Detections'

	properties_avdetection = None # string properties.avdetection

	_fields = {
		'properties_avdetection': {'name': 'properties.avdetection', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_avdetection=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_avdetection = properties_avdetection

entities.entity_map[Avdetection.id] = Avdetection
