# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="People" conversionOrder="2147483647" description="A person who is not on your side" displayName="Bad Guy" displayNamePlural="Bad Guys" id="maltego.BadGuy" largeIconResource="Person" smallIconResource="Person" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Person</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Person import Person

class BadGuy(Person):
	"""
	A person who is not on your side
	"""

	id = 'maltego.BadGuy'
	displayName = 'Bad Guy'
	displayNamePlural = 'Bad Guys'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[BadGuy.id] = BadGuy
