# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Tracking" conversionOrder="2147483647" description="A bank account identified by a bank name, branch number and account number" displayName="Bank Account" displayNamePlural="Bank Accounts" id="maltego.BankAccount" largeIconResource="BankAccount" smallIconResource="BankAccount" visible="true">
	   <Properties displayValue="bank.accnumber" value="bank.accnumber">
	      <Fields>
	         <Field description="Bank account number" displayName="Account Number" hidden="false" name="bank.accnumber" nullable="true" readonly="false" type="string">
	            <SampleValue>1122334455</SampleValue>
	         </Field>
	         <Field description="Bank name" displayName="Bank" hidden="false" name="bank.name" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="Bank branch code" displayName="Branch Code" hidden="false" name="bank.branch" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class BankAccount(entities.MaltegoEntity):
	"""
	A bank account identified by a bank name, branch number and account number
	"""

	id = 'maltego.BankAccount'
	displayName = 'Bank Account'
	displayNamePlural = 'Bank Accounts'

	bank_accnumber = None # string bank.accnumber
	bank_name = None # string bank.name
	bank_branch = None # string bank.branch

	_fields = {
		'bank_accnumber': {'name': 'bank.accnumber', 'type': 'string', 'nullable': 'true'},
		'bank_name': {'name': 'bank.name', 'type': 'string', 'nullable': 'true'},
		'bank_branch': {'name': 'bank.branch', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, bank_accnumber=None, bank_name=None, bank_branch=None, **kwargs):
		super().__init__(value, **kwargs)
		self.bank_accnumber = bank_accnumber
		self.bank_name = bank_name
		self.bank_branch = bank_branch

entities.entity_map[BankAccount.id] = BankAccount
