# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="2147483647" description="Banner" displayName="Banner" displayNamePlural="Banners" id="maltego.Banner" largeIconResource="Banner" smallIconResource="Banner" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Phrase</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Phrase import Phrase

class Banner(Phrase):
	"""
	Banner
	"""

	id = 'maltego.Banner'
	displayName = 'Banner'
	displayNamePlural = 'Banners'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[Banner.id] = Banner
