# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="Behaviour" displayName="Behaviour" displayNamePlural="Behaviours" id="maltego.Behaviour" largeIconResource="Spider" smallIconResource="Spider" visible="true">
	   <Properties displayValue="properties.behaviour" value="properties.behaviour">
	      <Fields>
	         <Field description="" displayName="Behaviour" hidden="false" name="properties.behaviour" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Behaviour(entities.MaltegoEntity):
	"""
	Behaviour
	"""

	id = 'maltego.Behaviour'
	displayName = 'Behaviour'
	displayNamePlural = 'Behaviours'

	properties_behaviour = None # string properties.behaviour

	_fields = {
		'properties_behaviour': {'name': 'properties.behaviour', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_behaviour=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_behaviour = properties_behaviour

entities.entity_map[Behaviour.id] = Behaviour
