# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Penetration Testing" conversionOrder="2147483647" description="A Relationship identified by BuiltWith" displayName="BuiltWith Relationship" displayNamePlural="BuiltWith Relationships" id="maltego.BuiltWithRelationship" largeIconResource="BuiltWith" smallIconResource="BuiltWith" visible="true">
	   <Properties displayValue="properties.builtwithrelationship" value="properties.builtwithrelationship">
	      <Fields>
	         <Field description="" displayName="BuiltWith Relationship" hidden="false" name="properties.builtwithrelationship" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	         <Field description="" displayName="Matches" hidden="true" name="matches" nullable="true" readonly="true" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class BuiltWithRelationship(entities.MaltegoEntity):
	"""
	A Relationship identified by BuiltWith
	"""

	id = 'maltego.BuiltWithRelationship'
	displayName = 'BuiltWith Relationship'
	displayNamePlural = 'BuiltWith Relationships'

	properties_builtwithrelationship = None # string properties.builtwithrelationship
	matches = None # string matches

	_fields = {
		'properties_builtwithrelationship': {'name': 'properties.builtwithrelationship', 'type': 'string', 'nullable': 'true'},
		'matches': {'name': 'matches', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_builtwithrelationship=None, matches=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_builtwithrelationship = properties_builtwithrelationship
		self.matches = matches

entities.entity_map[BuiltWithRelationship.id] = BuiltWithRelationship
