# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Transportation" conversionOrder="2147483647" description="A large motor vehicle that carries passengers by road" displayName="Bus" displayNamePlural="Busses" id="maltego.Bus" largeIconResource="Bus" smallIconResource="Bus" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Transport</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields>
	         <Field description="Make of the bus" displayName="Make" hidden="false" name="transport.make" nullable="true" readonly="false" type="string">
	            <SampleValue>Transit bus</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Transport import Transport

class Bus(Transport):
	"""
	A large motor vehicle that carries passengers by road
	"""

	id = 'maltego.Bus'
	displayName = 'Bus'
	displayNamePlural = 'Busses'

	transport_make = None # string transport.make

	_fields = {
		'transport_make': {'name': 'transport.make', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, transport_make=None, **kwargs):
		super().__init__(value, **kwargs)
		self.transport_make = transport_make

entities.entity_map[Bus.id] = Bus
