# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="2147483647" description="A place of worship" displayName="Church" displayNamePlural="Churches" id="maltego.Church" largeIconResource="Church" smallIconResource="Church" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Location</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields>
	         <Field description="" displayName="Name" hidden="false" name="location.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Notre Dame Cathedral</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Location import Location

class Church(Location):
	"""
	A place of worship
	"""

	id = 'maltego.Church'
	displayName = 'Church'
	displayNamePlural = 'Churches'

	location_name = None # string location.name

	_fields = {
		'location_name': {'name': 'location.name', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, location_name=None, **kwargs):
		super().__init__(value, **kwargs)
		self.location_name = location_name

entities.entity_map[Church.id] = Church
