# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="2147483647" description="A relatively large and permanent settlement" displayName="City" displayNamePlural="Cities" id="maltego.City" largeIconResource="Geography" smallIconResource="Geography" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Location</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Location import Location

class City(Location):
	"""
	A relatively large and permanent settlement
	"""

	id = 'maltego.City'
	displayName = 'City'
	displayNamePlural = 'Cities'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[City.id] = City
