# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Devices" conversionOrder="2147483647" description="An electronic device for storing and processing data" displayName="Computer" displayNamePlural="Computers" id="maltego.Computer" largeIconResource="TerminalGolden" smallIconResource="TerminalGolden" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Device</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="device" value="device">
	      <Fields>
	         <Field description="device" displayName="Device" hidden="false" name="device" nullable="true" readonly="false" type="string">
	            <SampleValue>PC</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Device import Device

class Computer(Device):
	"""
	An electronic device for storing and processing data
	"""

	id = 'maltego.Computer'
	displayName = 'Computer'
	displayNamePlural = 'Computers'

	device = None # string device

	_fields = {
		'device': {'name': 'device', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, device=None, **kwargs):
		super().__init__(value, **kwargs)
		self.device = device

entities.entity_map[Computer.id] = Computer
