# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Groups" conversionOrder="2147483647" description="A business organization" displayName="Company" displayNamePlural="Companies" id="maltego.Company" largeIconResource="Company" smallIconResource="Company" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Organization</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="Name of the company" displayName="Name" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Paterva</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Organization import Organization

class Company(Organization):
	"""
	A business organization
	"""

	id = 'maltego.Company'
	displayName = 'Company'
	displayNamePlural = 'Companies'

	title = None # string title

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title

entities.entity_map[Company.id] = Company
