# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Events" conversionOrder="2147483647" description="A conversation via email" displayName="Conversation (Email)" displayNamePlural="Conversations (Email)" id="maltego.ConversationEmail" largeIconResource="EmailConversation" smallIconResource="EmailConversation" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Conversation</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields>
	         <Field description="The email address of the sender" displayName="Sender Email" hidden="false" name="email" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="The email address of the recipients" displayName="Recipient Emails" hidden="false" name="email.recipients" nullable="true" readonly="false" type="string[]">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Conversation import Conversation

class ConversationEmail(Conversation):
	"""
	A conversation via email
	"""

	id = 'maltego.ConversationEmail'
	displayName = 'Conversation (Email)'
	displayNamePlural = 'Conversations (Email)'

	email = None # string email
	email_recipients = None # string[] email.recipients

	_fields = {
		'email': {'name': 'email', 'type': 'string', 'nullable': 'true'},
		'email_recipients': {'name': 'email.recipients', 'type': 'string[]', 'nullable': 'true'},
	}

	def __init__(self, value, email=None, email_recipients=None, **kwargs):
		super().__init__(value, **kwargs)
		self.email = email
		self.email_recipients = email_recipients

entities.entity_map[ConversationEmail.id] = ConversationEmail
