# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Events" conversionOrder="2147483647" description="A form of communication between two or more people" displayName="Conversation" displayNamePlural="Conversations" id="maltego.Conversation" largeIconResource="MeetingSocial" smallIconResource="MeetingSocial" visible="true">
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="The event name" displayName="Title" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Conversation</SampleValue>
	         </Field>
	         <Field description="The people involved" displayName="People" hidden="false" name="people" nullable="true" readonly="false" type="string[]">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Conversation(entities.MaltegoEntity):
	"""
	A form of communication between two or more people
	"""

	id = 'maltego.Conversation'
	displayName = 'Conversation'
	displayNamePlural = 'Conversations'

	title = None # string title
	people = None # string[] people

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
		'people': {'name': 'people', 'type': 'string[]', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, people=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title
		self.people = people

entities.entity_map[Conversation.id] = Conversation
