# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="2147483647" description="A nation with its own government, occupying a particular territory" displayName="Country" displayNamePlural="Countries" id="maltego.Country" largeIconResource="Geography" smallIconResource="Geography" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Location</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Location import Location

class Country(Location):
	"""
	A nation with its own government, occupying a particular territory
	"""

	id = 'maltego.Country'
	displayName = 'Country'
	displayNamePlural = 'Countries'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[Country.id] = Country
