# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="2147483647" description="A location where an illegal act took place" displayName="Crime Scene" displayNamePlural="Crime Scenes" id="maltego.CrimeScene" largeIconResource="CrimeScene" smallIconResource="CrimeScene" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Location</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Location import Location

class CrimeScene(Location):
	"""
	A location where an illegal act took place
	"""

	id = 'maltego.CrimeScene'
	displayName = 'Crime Scene'
	displayNamePlural = 'Crime Scenes'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[CrimeScene.id] = CrimeScene
