# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Devices" conversionOrder="2147483647" description="A personal computer in a form intended for regular use at a single location" displayName="Desktop Computer" displayNamePlural="Desktop Computers" id="maltego.DesktopComputer" largeIconResource="TerminalGolden" smallIconResource="TerminalGolden" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Computer</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Computer import Computer

class DesktopComputer(Computer):
	"""
	A personal computer in a form intended for regular use at a single location
	"""

	id = 'maltego.DesktopComputer'
	displayName = 'Desktop Computer'
	displayNamePlural = 'Desktop Computers'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[DesktopComputer.id] = DesktopComputer
