# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Devices" conversionOrder="2147483647" description="A device such as a phone or camera" displayName="Device" displayNamePlural="Devices" id="maltego.Device" largeIconResource="RemoteControlGolden" smallIconResource="RemoteControlGolden" visible="true">
	   <Properties displayValue="device" image="device" value="device">
	      <Fields>
	         <Field description="device" displayName="Device" hidden="false" name="device" nullable="true" readonly="false" type="string">
	            <SampleValue>Camera</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Device(entities.MaltegoEntity):
	"""
	A device such as a phone or camera
	"""

	id = 'maltego.Device'
	displayName = 'Device'
	displayNamePlural = 'Devices'

	device = None # string device

	_fields = {
		'device': {'name': 'device', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, device=None, **kwargs):
		super().__init__(value, **kwargs)
		self.device = device

entities.entity_map[Device.id] = Device
