# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="100" description="Domain Name System server name" displayName="DNS Name" displayNamePlural="DNS Names" id="maltego.DNSName" largeIconResource="DNS Name" smallIconResource="DNS Name" visible="true">
	   <Converter>
	      <Value>[-\w]{1,120}\.[-\w]{1,120}\.[-\w]{0,120}\.*[-\w]{1,4}\.*[a-zA-Z]+[-\w]{1,3}</Value>
	   </Converter>
	   <Properties displayValue="fqdn" value="fqdn">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="DNS Name" hidden="false" name="fqdn" nullable="true" readonly="false" type="string">
	            <SampleValue>alpine.paterva.com</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class DNSName(entities.MaltegoEntity):
	"""
	Domain Name System server name
	"""

	id = 'maltego.DNSName'
	displayName = 'DNS Name'
	displayNamePlural = 'DNS Names'

	fqdn = None # string fqdn

	_fields = {
		'fqdn': {'name': 'fqdn', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, fqdn=None, **kwargs):
		super().__init__(value, **kwargs)
		self.fqdn = fqdn

entities.entity_map[DNSName.id] = DNSName
