# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="120" description="An internet domain" displayName="Domain" displayNamePlural="Domains" id="maltego.Domain" largeIconResource="Domain" smallIconResource="Domain" visible="true">
	   <Converter>
	      <Value>[-\w]{1,120}\.[-\w]{1,4}\.*[-\w]{0,4}</Value>
	   </Converter>
	   <Properties displayValue="fqdn" value="fqdn">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="Domain Name" hidden="false" name="fqdn" nullable="true" readonly="false" type="string">
	            <SampleValue>paterva.com</SampleValue>
	         </Field>
	         <Field description="" displayName="WHOIS Info" hidden="false" name="whois-info" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Domain(entities.MaltegoEntity):
	"""
	An internet domain
	"""

	id = 'maltego.Domain'
	displayName = 'Domain'
	displayNamePlural = 'Domains'

	fqdn = None # string fqdn
	whois_info = None # string whois-info

	_fields = {
		'fqdn': {'name': 'fqdn', 'type': 'string', 'nullable': 'true'},
		'whois_info': {'name': 'whois-info', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, fqdn=None, whois_info=None, **kwargs):
		super().__init__(value, **kwargs)
		self.fqdn = fqdn
		self.whois_info = whois_info

entities.entity_map[Domain.id] = Domain
