# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="An unlicensed dealer in narcotics" displayName="Drug Dealer" displayNamePlural="Drug Dealers" id="maltego.DrugDealer" largeIconResource="DrugDealer" smallIconResource="DrugDealer" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.BadGuy</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.BadGuy import BadGuy

class DrugDealer(BadGuy):
	"""
	An unlicensed dealer in narcotics
	"""

	id = 'maltego.DrugDealer'
	displayName = 'Drug Dealer'
	displayNamePlural = 'Drug Dealers'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[DrugDealer.id] = DrugDealer
