# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Groups" conversionOrder="2147483647" description="An institution dedicated to education such as a school or university" displayName="Education Institution" displayNamePlural="Education Institutions" id="maltego.EducationInstitution" largeIconResource="School" smallIconResource="School" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Organization</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="Name of the educational institution" displayName="Name" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>MIT</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Organization import Organization

class EducationInstitution(Organization):
	"""
	An institution dedicated to education such as a school or university
	"""

	id = 'maltego.EducationInstitution'
	displayName = 'Education Institution'
	displayNamePlural = 'Education Institutions'

	title = None # string title

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title

entities.entity_map[EducationInstitution.id] = EducationInstitution
