# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Personal" conversionOrder="80" description="An email mailbox to which email messages may be delivered" displayName="Email Address" displayNamePlural="Email Addresses" id="maltego.EmailAddress" largeIconResource="Email Address" smallIconResource="Email Address" visible="true">
	   <Converter>
	      <Value>(([ \t]*([a-zA-Z0-9\!\#\$\%\&amp;\'\*\+\-\/\=\?\^\_\`\{\|\}\~]+(\.[a-zA-Z0-9\!\#\$\%\&amp;\'\*\+\-\/\=\?\^\_\`\{\|\}\~]+)*)[ \t]*)|(\"([ \t]*([\x01-\x08\x0B\x0C\x0E-\x1F\x7F\x21\x23-\x5B\x5D-\x7E]|(\\[\x01-\x09\x0B\x0C\x0E-\x7F])))*[ \t]*\"))@[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\.[a-zA-Z]{2,6}</Value>
	   </Converter>
	   <Properties displayValue="email" value="email">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="Email Address" hidden="false" name="email" nullable="true" readonly="false" type="string">
	            <SampleValue>info@paterva.com</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class EmailAddress(entities.MaltegoEntity):
	"""
	An email mailbox to which email messages may be delivered
	"""

	id = 'maltego.EmailAddress'
	displayName = 'Email Address'
	displayNamePlural = 'Email Addresses'

	email = None # string email

	_fields = {
		'email': {'name': 'email', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, email=None, **kwargs):
		super().__init__(value, **kwargs)
		self.email = email

entities.entity_map[EmailAddress.id] = EmailAddress
