# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" conversionOrder="2147483647" description="Facebook Object" displayName="Facebook Object" displayNamePlural="Facebook Objects" id="maltego.FacebookObject" largeIconResource="Facebook">
	   <Properties value="facebook.object">
	      <Fields>
	         <Field displayName="Facebook Object" hidden="false" name="facebook.object" nullable="true" readonly="false" type="string">
	            <SampleValue>Status Message</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class FacebookObject(entities.MaltegoEntity):
	"""
	Facebook Object
	"""

	id = 'maltego.FacebookObject'
	displayName = 'Facebook Object'
	displayNamePlural = 'Facebook Objects'

	facebook_object = None # string facebook.object

	_fields = {
		'facebook_object': {'name': 'facebook.object', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, facebook_object=None, **kwargs):
		super().__init__(value, **kwargs)
		self.facebook_object = facebook_object
