# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A woman or girl" displayName="Female" displayNamePlural="Females" id="maltego.Female" largeIconResource="AdultFemale" smallIconResource="AdultFemale" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Person</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields>
	         <Field description="" displayName="First Names" hidden="false" name="person.firstnames" nullable="true" readonly="false" type="string">
	            <SampleValue>Jane</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Person import Person

class Female(Person):
	"""
	A woman or girl
	"""

	id = 'maltego.Female'
	displayName = 'Female'
	displayNamePlural = 'Females'

	person_firstnames = None # string person.firstnames

	_fields = {
		'person_firstnames': {'name': 'person.firstnames', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, person_firstnames=None, **kwargs):
		super().__init__(value, **kwargs)
		self.person_firstnames = person_firstnames

entities.entity_map[Female.id] = Female
