# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="Filesize" displayName="Filesize" displayNamePlural="Filesizes" id="maltego.Filesize" largeIconResource="Files" smallIconResource="Files" visible="true">
	   <Properties displayValue="properties.filesize" value="properties.filesize">
	      <Fields>
	         <Field description="" displayName="Filesize" hidden="false" name="properties.filesize" nullable="true" readonly="false" type="int">
	            <SampleValue>0</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Filesize(entities.MaltegoEntity):
	"""
	Filesize
	"""

	id = 'maltego.Filesize'
	displayName = 'Filesize'
	displayNamePlural = 'Filesizes'

	properties_filesize = None # int properties.filesize

	_fields = {
		'properties_filesize': {'name': 'properties.filesize', 'type': 'int', 'nullable': 'true'},
	}

	def __init__(self, value, properties_filesize=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_filesize = properties_filesize

entities.entity_map[Filesize.id] = Filesize
