# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Personal" conversionOrder="2147483647" description="A file stored internally in the graph" displayName="File" displayNamePlural="Files" id="maltego.File" largeIconResource="File" smallIconResource="File" visible="true">
	   <Properties displayValue="description" value="description">
	      <Fields>
	         <Field description="" displayName="Source" hidden="false" name="source" nullable="true" readonly="false" type="url" />
	         <Field description="" displayName="Description" hidden="false" name="description" nullable="true" readonly="false" type="string">
	            <SampleValue>File</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class File(entities.MaltegoEntity):
	"""
	A file stored internally in the graph
	"""

	id = 'maltego.File'
	displayName = 'File'
	displayNamePlural = 'Files'

	source = None # url source
	description = None # string description

	_fields = {
		'source': {'name': 'source', 'type': 'url', 'nullable': 'true'},
		'description': {'name': 'description', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, source=None, description=None, **kwargs):
		super().__init__(value, **kwargs)
		self.source = source
		self.description = description

entities.entity_map[File.id] = File
