# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" description="Filters entities based on certain attributes" displayName="Filter" id="maltego.FilterAction" largeIconResource="Filter" visible="false">
	   <BaseEntities>
	      <BaseEntity>maltego.MachineAction</BaseEntity>
	   </BaseEntities>
	</MaltegoEntity>

"""

from tedious.entities.maltego.MachineAction import MachineAction

class FilterAction(MachineAction):
	"""
	Filters entities based on certain attributes
	"""

	id = 'maltego.FilterAction'
	displayName = 'Filter'
	displayNamePlural = None


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)
