# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="First seen" displayName="First seen" displayNamePlural="First seens" id="maltego.Firstseen" largeIconResource="firstseen" smallIconResource="firstseen" visible="true">
	   <Properties displayValue="properties.firstseen" value="properties.firstseen">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="First seen" hidden="false" name="properties.firstseen" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>2015-12-12 06:20:55</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Firstseen(entities.MaltegoEntity):
	"""
	First seen
	"""

	id = 'maltego.Firstseen'
	displayName = 'First seen'
	displayNamePlural = 'First seens'

	properties_firstseen = None # string properties.firstseen

	_fields = {
		'properties_firstseen': {'name': 'properties.firstseen', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_firstseen=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_firstseen = properties_firstseen

entities.entity_map[Firstseen.id] = Firstseen
