# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A leader of a gang" displayName="Gang Leader" displayNamePlural="Gang Leaders" id="maltego.GangLeader" largeIconResource="GangBoss" smallIconResource="GangBoss" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.GangMember</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.GangMember import GangMember

class GangLeader(GangMember):
	"""
	A leader of a gang
	"""

	id = 'maltego.GangLeader'
	displayName = 'Gang Leader'
	displayNamePlural = 'Gang Leaders'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[GangLeader.id] = GangLeader
