# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A person who is part of a gang" displayName="Gang Member" displayNamePlural="Gang Members" id="maltego.GangMember" largeIconResource="GangMember" smallIconResource="GangMember" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.BadGuy</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.BadGuy import BadGuy

class GangMember(BadGuy):
	"""
	A person who is part of a gang
	"""

	id = 'maltego.GangMember'
	displayName = 'Gang Member'
	displayNamePlural = 'Gang Members'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[GangMember.id] = GangMember
