# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A person elected or appointed to be involved in the administration of a government" displayName="Government Official" displayNamePlural="Government Officials" id="maltego.GovernmentOfficial" largeIconResource="GovermentOfficial" smallIconResource="GovermentOfficial" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Person</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Person import Person

class GovernmentOfficial(Person):
	"""
	A person elected or appointed to be involved in the administration of a government
	"""

	id = 'maltego.GovernmentOfficial'
	displayName = 'Government Official'
	displayNamePlural = 'Government Officials'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[GovernmentOfficial.id] = GovernmentOfficial
