# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="200" description="A location on a World Geodetic System coordinate frame for Earth" displayName="GPS Coordinate" displayNamePlural="GPS Coordinates" id="maltego.GPS" largeIconResource="GPS" smallIconResource="GPS" visible="true">
	   <Converter>
	      <Value>^\s*([\-\d.]+)\s*,\s*([\-\d.]+)\s*$</Value>
	      <RegexGroups>
	         <RegexGroup property="latitude" />
	         <RegexGroup property="longitude" />
	      </RegexGroups>
	   </Converter>
	   <Properties displayValue="gps.coordinate" value="gps.coordinate">
	      <Fields>
	         <Field description="" displayName="GPS Coordinate" evaluator="maltego.replace" hidden="false" name="gps.coordinate" nullable="true" readonly="false" type="string">
	            <DefaultValue>$property(latitude),$property(longitude)</DefaultValue>
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Latitude" hidden="false" name="latitude" nullable="true" readonly="false" type="float">
	            <SampleValue>38.951633</SampleValue>
	         </Field>
	         <Field description="" displayName="Longitude" hidden="false" name="longitude" nullable="true" readonly="false" type="float">
	            <SampleValue>-77.14462</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	   <Actions>
	      <Action displayName="Google Maps Me!" name="maltego.spec.action.googlemaps" type="maltego.spec.action.type.browser">
	         <Config>http://maps.google.com/maps?ll=$property(latitude),$property(longitude)</Config>
	      </Action>
	   </Actions>
	</MaltegoEntity>

"""

import tedious.entities as entities

class GPS(entities.MaltegoEntity):
	"""
	A location on a World Geodetic System coordinate frame for Earth
	"""

	id = 'maltego.GPS'
	displayName = 'GPS Coordinate'
	displayNamePlural = 'GPS Coordinates'

	gps_coordinate = None # string gps.coordinate
	latitude = None # float latitude
	longitude = None # float longitude

	_fields = {
		'gps_coordinate': {'name': 'gps.coordinate', 'type': 'string', 'nullable': 'true'},
		'latitude': {'name': 'latitude', 'type': 'float', 'nullable': 'true'},
		'longitude': {'name': 'longitude', 'type': 'float', 'nullable': 'true'},
	}

	def __init__(self, value, gps_coordinate=None, latitude=None, longitude=None, **kwargs):
		super().__init__(value, **kwargs)
		self.gps_coordinate = gps_coordinate
		self.latitude = latitude
		self.longitude = longitude

entities.entity_map[GPS.id] = GPS
