# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Social Network" conversionOrder="2147483647" description="Twitter hashtag" displayName="Hashtag" displayNamePlural="Hashtags" id="maltego.hashtag" largeIconResource="NumericField" smallIconResource="NumericField" visible="true">
	   <Properties displayValue="twitter.hashtag" value="twitter.hashtag">
	      <Fields>
	         <Field description="" displayName="Hashtag" hidden="false" name="twitter.hashtag" nullable="true" readonly="false" type="string">
	            <SampleValue>#maltego</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class hashtag(entities.MaltegoEntity):
	"""
	Twitter hashtag
	"""

	id = 'maltego.hashtag'
	displayName = 'Hashtag'
	displayNamePlural = 'Hashtags'

	twitter_hashtag = None # string twitter.hashtag

	_fields = {
		'twitter_hashtag': {'name': 'twitter.hashtag', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, twitter_hashtag=None, **kwargs):
		super().__init__(value, **kwargs)
		self.twitter_hashtag = twitter_hashtag

entities.entity_map[hashtag.id] = hashtag
