# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="1337" description="Hash entity" displayName="Hash" displayNamePlural="Hashes" id="maltego.Hash" largeIconResource="Virus" smallIconResource="Virus" visible="true">
	   <Converter>
	      <Value>([0-9a-f]{32}|[0-9A-F]{32}|[0-9a-f]{40}|[0-9A-F]{40}|[0-9a-f]{64}|[0-9A-F]{64})</Value>
	   </Converter>
	   <Properties displayValue="properties.hash" value="properties.hash">
	      <Groups />
	      <Fields>
	         <Field description="A hash entity" displayName="Hash" hidden="false" name="properties.hash" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>af30fca836142d6a0b8672f1e8f53acf</SampleValue>
	         </Field>
	         <Field description="" displayName="Hash Type" hidden="false" name="type" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue> </SampleValue>
	         </Field>
	         <Field description="" displayName="Owner" hidden="false" name="owner" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Before" hidden="false" name="before" nullable="true" readonly="false" type="date" />
	         <Field description="" displayName="After" hidden="false" name="after" nullable="true" readonly="false" type="date" />
	         <Field description="" displayName="Included Media Types" hidden="false" name="includeMediaType" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Excluded Media Types" hidden="false" name="excludeMediaType" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Hash(entities.MaltegoEntity):
	"""
	Hash entity
	"""

	id = 'maltego.Hash'
	displayName = 'Hash'
	displayNamePlural = 'Hashes'

	properties_hash = None # string properties.hash
	type = None # string type
	owner = None # string owner
	before = None # date before
	after = None # date after
	includemediatype = None # string includeMediaType
	excludemediatype = None # string excludeMediaType

	_fields = {
		'properties_hash': {'name': 'properties.hash', 'type': 'string', 'nullable': 'true'},
		'type': {'name': 'type', 'type': 'string', 'nullable': 'true'},
		'owner': {'name': 'owner', 'type': 'string', 'nullable': 'true'},
		'before': {'name': 'before', 'type': 'date', 'nullable': 'true'},
		'after': {'name': 'after', 'type': 'date', 'nullable': 'true'},
		'includemediatype': {'name': 'includeMediaType', 'type': 'string', 'nullable': 'true'},
		'excludemediatype': {'name': 'excludeMediaType', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_hash=None, type=None, owner=None, before=None, after=None, includemediatype=None, excludemediatype=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_hash = properties_hash
		self.type = type
		self.owner = owner
		self.before = before
		self.after = after
		self.includemediatype = includemediatype
		self.excludemediatype = excludemediatype

entities.entity_map[Hash.id] = Hash
