# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="2147483647" description="A place of living" displayName="Home" displayNamePlural="Homes" id="maltego.Home" largeIconResource="Home" smallIconResource="Home" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Location</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Location import Location

class Home(Location):
	"""
	A place of living
	"""

	id = 'maltego.Home'
	displayName = 'Home'
	displayNamePlural = 'Homes'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[Home.id] = Home
