# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Tracking" conversionOrder="2147483647" description="A number which may be used to verify aspects of a person's personal identity" displayName="Identification Number" displayNamePlural="Identification Numbers" id="maltego.IdentificationNumber" largeIconResource="SSN" smallIconResource="SSN" visible="true">
	   <Properties displayValue="identification.number" value="identification.number">
	      <Fields>
	         <Field description="Identification number" displayName="Number" hidden="false" name="identification.number" nullable="true" readonly="false" type="string">
	            <SampleValue>1122334455</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class IdentificationNumber(entities.MaltegoEntity):
	"""
	A number which may be used to verify aspects of a person's personal identity
	"""

	id = 'maltego.IdentificationNumber'
	displayName = 'Identification Number'
	displayNamePlural = 'Identification Numbers'

	identification_number = None # string identification.number

	_fields = {
		'identification_number': {'name': 'identification.number', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, identification_number=None, **kwargs):
		super().__init__(value, **kwargs)
		self.identification_number = identification_number

entities.entity_map[IdentificationNumber.id] = IdentificationNumber
