# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Personal" conversionOrder="85" description="A visual representation of something" displayName="Image" displayNamePlural="Images" id="maltego.Image" largeIconResource="Image" smallIconResource="Image" visible="true">
	   <Converter>
	      <Value>(http[s]*://[-\w\.\:]*[^\s]*/([^\s]+\.(bmp|jpg|jpeg|png|gif))(\?[^\s]*)?)</Value>
	      <RegexGroups>
	         <RegexGroup property="url" />
	         <RegexGroup property="description" />
	      </RegexGroups>
	   </Converter>
	   <Properties displayValue="description" image="url" value="description">
	      <Fields>
	         <Field description="" displayName="Description" hidden="false" name="description" nullable="true" readonly="false" type="string">
	            <SampleValue>Image</SampleValue>
	         </Field>
	         <Field description="" displayName="URL" hidden="false" name="url" nullable="true" readonly="false" type="url" />
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Image(entities.MaltegoEntity):
	"""
	A visual representation of something
	"""

	id = 'maltego.Image'
	displayName = 'Image'
	displayNamePlural = 'Images'

	description = None # string description
	url = None # url url

	_fields = {
		'description': {'name': 'description', 'type': 'string', 'nullable': 'true'},
		'url': {'name': 'url', 'type': 'url', 'nullable': 'true'},
	}

	def __init__(self, value, description=None, url=None, **kwargs):
		super().__init__(value, **kwargs)
		self.description = description
		self.url = url

entities.entity_map[Image.id] = Image
