# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="Imphash" displayName="Import Hash" displayNamePlural="Import Hashs" id="maltego.Imphash" largeIconResource="DNACode" smallIconResource="DNACode" visible="true">
	   <Properties displayValue="properties.importhash" value="properties.importhash">
	      <Fields>
	         <Field description="Imphash" displayName="Import Hash" hidden="false" name="properties.importhash" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Imphash(entities.MaltegoEntity):
	"""
	Imphash
	"""

	id = 'maltego.Imphash'
	displayName = 'Import Hash'
	displayNamePlural = 'Import Hashs'

	properties_importhash = None # string properties.importhash

	_fields = {
		'properties_importhash': {'name': 'properties.importhash', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_importhash=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_importhash = properties_importhash

entities.entity_map[Imphash.id] = Imphash
