# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="Imports" displayName="Imports" displayNamePlural="Importses" id="maltego.Imports" largeIconResource="List" smallIconResource="List" visible="true">
	   <Properties displayValue="properties.imports" value="properties.imports">
	      <Fields>
	         <Field description="" displayName="Imports" hidden="false" name="properties.imports" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Imports(entities.MaltegoEntity):
	"""
	Imports
	"""

	id = 'maltego.Imports'
	displayName = 'Imports'
	displayNamePlural = 'Importses'

	properties_imports = None # string properties.imports

	_fields = {
		'properties_imports': {'name': 'properties.imports', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_imports=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_imports = properties_imports

entities.entity_map[Imports.id] = Imports
