# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Events" conversionOrder="2147483647" description="An event or occurrence (for instance a murder or robbery)" displayName="Incident" displayNamePlural="Incidents" id="maltego.Incident" largeIconResource="Murder" smallIconResource="Murder" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Event</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="The event name" displayName="Title" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Murder</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Event import Event

class Incident(Event):
	"""
	An event or occurrence (for instance a murder or robbery)
	"""

	id = 'maltego.Incident'
	displayName = 'Incident'
	displayNamePlural = 'Incidents'

	title = None # string title

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title

entities.entity_map[Incident.id] = Incident
