# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="60" description="An IP version 4 address" displayName="IPv4 Address" displayNamePlural="IPv4 Addresses" id="maltego.IPv4Address" largeIconResource="NetCardGolden" smallIconResource="NetCardGolden" visible="true">
	   <Converter>
	      <Value>(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)</Value>
	   </Converter>
	   <Properties displayValue="ipv4-address" value="ipv4-address">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="IP Address" hidden="false" name="ipv4-address" nullable="true" readonly="false" type="string">
	            <SampleValue>74.207.243.85</SampleValue>
	         </Field>
	         <Field description="" displayName="Internal" hidden="false" name="ipaddress.internal" nullable="true" readonly="false" type="boolean">
	            <SampleValue>false</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class IPv4Address(entities.MaltegoEntity):
	"""
	An IP version 4 address
	"""

	id = 'maltego.IPv4Address'
	displayName = 'IPv4 Address'
	displayNamePlural = 'IPv4 Addresses'

	ipv4_address = None # string ipv4-address
	ipaddress_internal = None # boolean ipaddress.internal

	_fields = {
		'ipv4_address': {'name': 'ipv4-address', 'type': 'string', 'nullable': 'true'},
		'ipaddress_internal': {'name': 'ipaddress.internal', 'type': 'boolean', 'nullable': 'true'},
	}

	def __init__(self, value, ipv4_address=None, ipaddress_internal=None, **kwargs):
		super().__init__(value, **kwargs)
		self.ipv4_address = ipv4_address
		self.ipaddress_internal = ipaddress_internal

entities.entity_map[IPv4Address.id] = IPv4Address
