# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A public official appointed to decide cases in a court of law" displayName="Judge" displayNamePlural="Judges" id="maltego.Judge" largeIconResource="Judge" smallIconResource="Judge" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.GoodGuy</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.GoodGuy import GoodGuy

class Judge(GoodGuy):
	"""
	A public official appointed to decide cases in a court of law
	"""

	id = 'maltego.Judge'
	displayName = 'Judge'
	displayNamePlural = 'Judges'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[Judge.id] = Judge
