# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A person charged with the apprehension of criminals, the prevention and detection of crime and the maintenance of public order" displayName="Law Enforcement Officer" displayNamePlural="Law Enforcement Officers" id="maltego.LawOfficer" largeIconResource="LawEnforcementOfficer" smallIconResource="LawEnforcementOfficer" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.GoodGuy</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.GoodGuy import GoodGuy

class LawOfficer(GoodGuy):
	"""
	A person charged with the apprehension of criminals, the prevention and detection of crime and the maintenance of public order
	"""

	id = 'maltego.LawOfficer'
	displayName = 'Law Enforcement Officer'
	displayNamePlural = 'Law Enforcement Officers'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[LawOfficer.id] = LawOfficer
