# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A person who practices law" displayName="Lawyer / Advocate" displayNamePlural="Lawyers / Advocates" id="maltego.Lawyer" largeIconResource="Lawyer" smallIconResource="Lawyer" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Person</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Person import Person

class Lawyer(Person):
	"""
	A person who practices law
	"""

	id = 'maltego.Lawyer'
	displayName = 'Lawyer / Advocate'
	displayNamePlural = 'Lawyers / Advocates'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[Lawyer.id] = Lawyer
