# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="2147483647" description="A location on Mother Earth" displayName="Location" displayNamePlural="Locations" id="maltego.Location" largeIconResource="Location" smallIconResource="Location" visible="true">
	   <Properties displayValue="location.name" value="location.name">
	      <Fields>
	         <Field description="" displayName="Name" evaluator="maltego.replace" hidden="false" name="location.name" nullable="true" readonly="false" type="string">
	            <DefaultValue>$trim($property(city), $property(country))</DefaultValue>
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Country" hidden="false" name="country" nullable="true" readonly="false" type="string">
	            <SampleValue>South Africa</SampleValue>
	         </Field>
	         <Field description="" displayName="City" hidden="false" name="city" nullable="true" readonly="false" type="string">
	            <SampleValue>Pretoria</SampleValue>
	         </Field>
	         <Field description="" displayName="Street Address" hidden="false" name="streetaddress" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Area" hidden="false" name="location.area" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Area Code" hidden="false" name="location.areacode" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Country Code" hidden="false" name="countrycode" nullable="true" readonly="false" type="string">
	            <SampleValue>ZA</SampleValue>
	         </Field>
	         <Field description="" displayName="Longitude" hidden="false" name="longitude" nullable="true" readonly="false" type="float">
	            <SampleValue>0.0</SampleValue>
	         </Field>
	         <Field description="" displayName="Latitude" hidden="false" name="latitude" nullable="true" readonly="false" type="float">
	            <SampleValue>0.0</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	   <Overlays>
	      <Overlay position="SW" propertyName="countrycode" type="image" />
	   </Overlays>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Location(entities.MaltegoEntity):
	"""
	A location on Mother Earth
	"""

	id = 'maltego.Location'
	displayName = 'Location'
	displayNamePlural = 'Locations'

	location_name = None # string location.name
	country = None # string country
	city = None # string city
	streetaddress = None # string streetaddress
	location_area = None # string location.area
	location_areacode = None # string location.areacode
	countrycode = None # string countrycode
	longitude = None # float longitude
	latitude = None # float latitude

	_fields = {
		'location_name': {'name': 'location.name', 'type': 'string', 'nullable': 'true'},
		'country': {'name': 'country', 'type': 'string', 'nullable': 'true'},
		'city': {'name': 'city', 'type': 'string', 'nullable': 'true'},
		'streetaddress': {'name': 'streetaddress', 'type': 'string', 'nullable': 'true'},
		'location_area': {'name': 'location.area', 'type': 'string', 'nullable': 'true'},
		'location_areacode': {'name': 'location.areacode', 'type': 'string', 'nullable': 'true'},
		'countrycode': {'name': 'countrycode', 'type': 'string', 'nullable': 'true'},
		'longitude': {'name': 'longitude', 'type': 'float', 'nullable': 'true'},
		'latitude': {'name': 'latitude', 'type': 'float', 'nullable': 'true'},
	}

	def __init__(self, value, location_name=None, country=None, city=None, streetaddress=None, location_area=None, location_areacode=None, countrycode=None, longitude=None, latitude=None, **kwargs):
		super().__init__(value, **kwargs)
		self.location_name = location_name
		self.country = country
		self.city = city
		self.streetaddress = streetaddress
		self.location_area = location_area
		self.location_areacode = location_areacode
		self.countrycode = countrycode
		self.longitude = longitude
		self.latitude = latitude

entities.entity_map[Location.id] = Location
