# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Tracking" conversionOrder="2147483647" description="The unique hardware address of a network device" displayName="MAC Address" displayNamePlural="MAC Addresses" id="maltego.MacAddress" largeIconResource="MacAddress" smallIconResource="MacAddress" visible="true">
	   <Properties displayValue="macaddress" value="macaddress">
	      <Fields>
	         <Field description="" displayName="MAC Address" hidden="false" name="macaddress" nullable="true" readonly="false" type="string">
	            <SampleValue>01:21:33:71:33:75</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class MacAddress(entities.MaltegoEntity):
	"""
	The unique hardware address of a network device
	"""

	id = 'maltego.MacAddress'
	displayName = 'MAC Address'
	displayNamePlural = 'MAC Addresses'

	macaddress = None # string macaddress

	_fields = {
		'macaddress': {'name': 'macaddress', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, macaddress=None, **kwargs):
		super().__init__(value, **kwargs)
		self.macaddress = macaddress

entities.entity_map[MacAddress.id] = MacAddress
