# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" description="A Maltego Transform Action" displayName="Transform Action" id="maltego.MachineTransformAction" largeIconResource="Transform" visible="false">
	   <BaseEntities>
	      <BaseEntity>maltego.MachineAction</BaseEntity>
	   </BaseEntities>
	</MaltegoEntity>

"""

from tedious.entities.maltego.MachineAction import MachineAction

class MachineTransformAction(MachineAction):
	"""
	A Maltego Transform Action
	"""

	id = 'maltego.MachineTransformAction'
	displayName = 'Transform Action'
	displayNamePlural = None


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)
