# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" conversionOrder="2147483647" description="An action performed by a Maltego Machine" displayName="Machine Action" displayNamePlural="Machine Actions" id="maltego.MachineAction" largeIconResource="Script" visible="false">
	
	   <Properties value="action">
	      <Fields>
	         <Field displayName="Action name" hidden="false" name="name" nullable="true" readonly="false" type="string">
	            <SampleValue>action</SampleValue>
	         </Field>
	         <Field displayName="Action detail" hidden="false" name="action" nullable="true" readonly="false" type="string">
	            <SampleValue>action()</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	
	
	</MaltegoEntity>

"""

import tedious.entities as entities

class MachineAction(entities.MaltegoEntity):
	"""
	An action performed by a Maltego Machine
	"""

	id = 'maltego.MachineAction'
	displayName = 'Machine Action'
	displayNamePlural = 'Machine Actions'

	name = None # string name
	action = None # string action

	_fields = {
		'name': {'name': 'name', 'type': 'string', 'nullable': 'true'},
		'action': {'name': 'action', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, name=None, action=None, **kwargs):
		super().__init__(value, **kwargs)
		self.name = name
		self.action = action
