# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" conversionOrder="2147483647" description="A machine input representing the whole graph" displayName="Whole Graph" id="maltego.MachineGlobalInput" largeIconResource="Graph" visible="false">
	
	   <Properties value="name">
	      <Fields>
	         <Field displayName="Name" hidden="false" name="name" nullable="true" readonly="true" type="string">
	            <SampleValue>Whole Graph</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	
	
	</MaltegoEntity>

"""

import tedious.entities as entities

class MachineGlobalInput(entities.MaltegoEntity):
	"""
	A machine input representing the whole graph
	"""

	id = 'maltego.MachineGlobalInput'
	displayName = 'Whole Graph'
	displayNamePlural = None

	name = None # string name

	_fields = {
		'name': {'name': 'name', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, name=None, **kwargs):
		super().__init__(value, **kwargs)
		self.name = name
