# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Events" conversionOrder="2147483647" description="A gathering of people" displayName="Meeting" displayNamePlural="Meetings" id="maltego.Meeting" largeIconResource="MeetingSocial" smallIconResource="MeetingSocial" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Event</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="The event name" displayName="Title" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Meeting</SampleValue>
	         </Field>
	         <Field description="The people involved" displayName="People" hidden="false" name="people" nullable="true" readonly="false" type="string[]">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Event import Event

class Meeting(Event):
	"""
	A gathering of people
	"""

	id = 'maltego.Meeting'
	displayName = 'Meeting'
	displayNamePlural = 'Meetings'

	title = None # string title
	people = None # string[] people

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
		'people': {'name': 'people', 'type': 'string[]', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, people=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title
		self.people = people

entities.entity_map[Meeting.id] = Meeting
