# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Events" conversionOrder="2147483647" description="A gathering of people for discussion or entertainment" displayName="Meeting (Social)" displayNamePlural="Meetings (Social)" id="maltego.MeetingSocial" largeIconResource="MeetingSocial" smallIconResource="MeetingSocial" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Meeting</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Meeting import Meeting

class MeetingSocial(Meeting):
	"""
	A gathering of people for discussion or entertainment
	"""

	id = 'maltego.MeetingSocial'
	displayName = 'Meeting (Social)'
	displayNamePlural = 'Meetings (Social)'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[MeetingSocial.id] = MeetingSocial
