# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A person in the armed services who holds a position of authority or command" displayName="Military Officer" displayNamePlural="Military Officers" id="maltego.MilitaryOfficer" largeIconResource="MilitaryOfficer" smallIconResource="MilitaryOfficer" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.GoodGuy</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.GoodGuy import GoodGuy

class MilitaryOfficer(GoodGuy):
	"""
	A person in the armed services who holds a position of authority or command
	"""

	id = 'maltego.MilitaryOfficer'
	displayName = 'Military Officer'
	displayNamePlural = 'Military Officers'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[MilitaryOfficer.id] = MilitaryOfficer
