# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Weapons" conversionOrder="2147483647" description="A self-propelled or remote-controlled weapon that carries an explosive or the device used to fire it" displayName="Missile / RPG" displayNamePlural="Missiles / RPGs" id="maltego.Missile" largeIconResource="MissileRPG" smallIconResource="MissileRPG" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Weapon</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="weapon.type" value="weapon.type">
	      <Fields>
	         <Field description="Weapon type" displayName="Type" hidden="false" name="weapon.type" nullable="true" readonly="false" type="string">
	            <SampleValue>RPG</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Weapon import Weapon

class Missile(Weapon):
	"""
	A self-propelled or remote-controlled weapon that carries an explosive or the device used to fire it
	"""

	id = 'maltego.Missile'
	displayName = 'Missile / RPG'
	displayNamePlural = 'Missiles / RPGs'

	weapon_type = None # string weapon.type

	_fields = {
		'weapon_type': {'name': 'weapon.type', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, weapon_type=None, **kwargs):
		super().__init__(value, **kwargs)
		self.weapon_type = weapon_type

entities.entity_map[Missile.id] = Missile
