# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="Mutex" displayName="Mutex" displayNamePlural="Mutexs" id="maltego.Mutex" largeIconResource="Password" smallIconResource="Password" visible="true">
	   <Properties displayValue="properties.mutex" value="properties.mutex">
	      <Fields>
	         <Field description="" displayName="Mutex" hidden="false" name="properties.mutex" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Mutex(entities.MaltegoEntity):
	"""
	Mutex
	"""

	id = 'maltego.Mutex'
	displayName = 'Mutex'
	displayNamePlural = 'Mutexs'

	properties_mutex = None # string properties.mutex

	_fields = {
		'properties_mutex': {'name': 'properties.mutex', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_mutex=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_mutex = properties_mutex

entities.entity_map[Mutex.id] = Mutex
