# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="70" description="A range of IP version 4 addresses" displayName="Netblock" displayNamePlural="Netblocks" id="maltego.Netblock" largeIconResource="ClusterGolden" smallIconResource="ClusterGolden" visible="true">
	   <Converter>
	      <Value>(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?) *- *(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)</Value>
	   </Converter>
	   <Properties displayValue="ipv4-range" value="ipv4-range">
	      <Fields>
	         <Field description="" displayName="IP Range" hidden="false" name="ipv4-range" nullable="true" readonly="false" type="string">
	            <SampleValue>74.207.243.0-74.207.243.255</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Netblock(entities.MaltegoEntity):
	"""
	A range of IP version 4 addresses
	"""

	id = 'maltego.Netblock'
	displayName = 'Netblock'
	displayNamePlural = 'Netblocks'

	ipv4_range = None # string ipv4-range

	_fields = {
		'ipv4_range': {'name': 'ipv4-range', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, ipv4_range=None, **kwargs):
		super().__init__(value, **kwargs)
		self.ipv4_range = ipv4_range

entities.entity_map[Netblock.id] = Netblock
