# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Locations" conversionOrder="2147483647" description="Nominatim Location" displayName="Nominatim Location" displayNamePlural="Nominatim Locations" id="maltego.NominatimLocation" largeIconResource="Location" smallIconResource="Location" visible="true">
	   <Properties displayValue="nominatimlocation" value="nominatimlocation">
	      <Fields>
	         <Field description="" displayName="Nominatim Location" hidden="false" name="nominatimlocation" nullable="true" readonly="false" type="string">
	            <SampleValue>Pretoria, South Africa</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class NominatimLocation(entities.MaltegoEntity):
	"""
	Nominatim Location
	"""

	id = 'maltego.NominatimLocation'
	displayName = 'Nominatim Location'
	displayNamePlural = 'Nominatim Locations'

	nominatimlocation = None # string nominatimlocation

	_fields = {
		'nominatimlocation': {'name': 'nominatimlocation', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, nominatimlocation=None, **kwargs):
		super().__init__(value, **kwargs)
		self.nominatimlocation = nominatimlocation

entities.entity_map[NominatimLocation.id] = NominatimLocation
