# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="2147483647" description="A DNS name server record" displayName="NS Record" displayNamePlural="NS Records" id="maltego.NSRecord" largeIconResource="NS Record" smallIconResource="NS Record" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.DNSName</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="fqdn" value="fqdn">
	      <Fields>
	         <Field description="" displayName="NS Record" hidden="false" name="fqdn" nullable="true" readonly="false" type="string">
	            <SampleValue>ns1.linode.com</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.DNSName import DNSName

class NSRecord(DNSName):
	"""
	A DNS name server record
	"""

	id = 'maltego.NSRecord'
	displayName = 'NS Record'
	displayNamePlural = 'NS Records'

	fqdn = None # string fqdn

	_fields = {
		'fqdn': {'name': 'fqdn', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, fqdn=None, **kwargs):
		super().__init__(value, **kwargs)
		self.fqdn = fqdn

entities.entity_map[NSRecord.id] = NSRecord
