# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Weapons" conversionOrder="2147483647" description="A weapon whose explosive power derives from a nuclear reaction" displayName="Nuclear Weapon" displayNamePlural="Nuclear Weapons" id="maltego.NuclearWeapon" largeIconResource="Atom" smallIconResource="Atom" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.WMD</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="weapon.type" value="weapon.type">
	      <Fields>
	         <Field description="Weapon type" displayName="Type" hidden="false" name="weapon.type" nullable="true" readonly="false" type="string">
	            <SampleValue>Hydrogen Bomb</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.WMD import WMD

class NuclearWeapon(WMD):
	"""
	A weapon whose explosive power derives from a nuclear reaction
	"""

	id = 'maltego.NuclearWeapon'
	displayName = 'Nuclear Weapon'
	displayNamePlural = 'Nuclear Weapons'

	weapon_type = None # string weapon.type

	_fields = {
		'weapon_type': {'name': 'weapon.type', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, weapon_type=None, **kwargs):
		super().__init__(value, **kwargs)
		self.weapon_type = weapon_type

entities.entity_map[NuclearWeapon.id] = NuclearWeapon
