# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Groups" conversionOrder="2147483647" description="A socializing service on the Internet such as Facebook, an IRC channel or a mailing list" displayName="Online Group" displayNamePlural="Online Groups" id="maltego.OnlineGroup" largeIconResource="OnlineGroup" smallIconResource="OnlineGroup" visible="true">
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="Name of the online group" displayName="Name" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Facebook</SampleValue>
	         </Field>
	         <Field description="Web reference" displayName="URL" hidden="false" name="url" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class OnlineGroup(entities.MaltegoEntity):
	"""
	A socializing service on the Internet such as Facebook, an IRC channel or a mailing list
	"""

	id = 'maltego.OnlineGroup'
	displayName = 'Online Group'
	displayNamePlural = 'Online Groups'

	title = None # string title
	url = None # string url

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
		'url': {'name': 'url', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, url=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title
		self.url = url

entities.entity_map[OnlineGroup.id] = OnlineGroup
