# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Groups" conversionOrder="2147483647" description="A social group which distributes tasks for a collective goal" displayName="Organization" displayNamePlural="Organizations" id="maltego.Organization" largeIconResource="Organization" smallIconResource="Organization" visible="true">
	   <Properties displayValue="title" value="title">
	      <Groups />
	      <Fields>
	         <Field description="Name of the organization" displayName="Name" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>United Nations</SampleValue>
	         </Field>
	         <Field description="" hidden="false" name="StartDate" nullable="true" readonly="false" type="string[]">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Organization(entities.MaltegoEntity):
	"""
	A social group which distributes tasks for a collective goal
	"""

	id = 'maltego.Organization'
	displayName = 'Organization'
	displayNamePlural = 'Organizations'

	title = None # string title
	startdate = None # string[] StartDate

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
		'startdate': {'name': 'StartDate', 'type': 'string[]', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, startdate=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title
		self.startdate = startdate

entities.entity_map[Organization.id] = Organization
