# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Tracking" conversionOrder="2147483647" description="A number, issued by a national government, which certifies, for the purpose of international travel, the identity of a person" displayName="Passport Number" displayNamePlural="Passport Numbers" id="maltego.PassportNumber" largeIconResource="Passport" smallIconResource="Passport" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.IdentificationNumber</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.IdentificationNumber import IdentificationNumber

class PassportNumber(IdentificationNumber):
	"""
	A number, issued by a national government, which certifies, for the purpose of international travel, the identity of a person
	"""

	id = 'maltego.PassportNumber'
	displayName = 'Passport Number'
	displayNamePlural = 'Passport Numbers'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[PassportNumber.id] = PassportNumber
