# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="PE Resource" displayName="PE Resource" displayNamePlural="PE Resources" id="maltego.Peresource" largeIconResource="ImageField" smallIconResource="ImageField" visible="true">
	   <Properties displayValue="properties.peresource" value="properties.peresource">
	      <Fields>
	         <Field description="" displayName="PE Resource" hidden="false" name="properties.peresource" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Peresource(entities.MaltegoEntity):
	"""
	PE Resource
	"""

	id = 'maltego.Peresource'
	displayName = 'PE Resource'
	displayNamePlural = 'PE Resources'

	properties_peresource = None # string properties.peresource

	_fields = {
		'properties_peresource': {'name': 'properties.peresource', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_peresource=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_peresource = properties_peresource

entities.entity_map[Peresource.id] = Peresource
