# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Personal" conversionOrder="2147483647" description="A phone number of a mobile phone" displayName="Phone Number (Mobile)" displayNamePlural="Phone Numbers (Mobile)" id="maltego.PhoneNumberMobile" largeIconResource="MobilePhoneGolden" smallIconResource="MobilePhoneGolden" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.PhoneNumber</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.PhoneNumber import PhoneNumber

class PhoneNumberMobile(PhoneNumber):
	"""
	A phone number of a mobile phone
	"""

	id = 'maltego.PhoneNumberMobile'
	displayName = 'Phone Number (Mobile)'
	displayNamePlural = 'Phone Numbers (Mobile)'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[PhoneNumberMobile.id] = PhoneNumberMobile
