# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Personal" conversionOrder="110" description="A telephone number" displayName="Phone Number" displayNamePlural="Phone Numbers" id="maltego.PhoneNumber" largeIconResource="Phone" smallIconResource="Phone" visible="true">
	   <Converter>
	      <Value>(\+\d{1,3})??[\-\ ]??([\(]?\d{1,3}[\)]?)??[\-\ ]?(\d{3,4})[\-\ ]?(\d{3,4})$</Value>
	      <RegexGroups>
	         <RegexGroup property="phonenumber.countrycode" />
	         <RegexGroup property="phonenumber.citycode" />
	         <RegexGroup property="phonenumber.areacode" />
	         <RegexGroup property="phonenumber.lastnumbers" />
	      </RegexGroups>
	   </Converter>
	   <Properties displayValue="phonenumber" value="phonenumber">
	      <Fields>
	         <Field description="" displayName="Phone Number" evaluator="maltego.replace" hidden="false" name="phonenumber" nullable="true" readonly="false" type="string">
	            <DefaultValue>$trim($property(phonenumber.countrycode) $property(phonenumber.citycode) $property(phonenumber.areacode) $property(phonenumber.lastnumbers))</DefaultValue>
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Country Code" hidden="false" name="phonenumber.countrycode" nullable="true" readonly="false" type="string">
	            <SampleValue>27</SampleValue>
	         </Field>
	         <Field description="" displayName="City Code" hidden="false" name="phonenumber.citycode" nullable="true" readonly="false" type="string">
	            <SampleValue>12</SampleValue>
	         </Field>
	         <Field description="" displayName="Area Code" hidden="false" name="phonenumber.areacode" nullable="true" readonly="false" type="string">
	            <SampleValue>667</SampleValue>
	         </Field>
	         <Field description="" displayName="Last Digits" hidden="false" name="phonenumber.lastnumbers" nullable="true" readonly="false" type="string">
	            <SampleValue>0000</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class PhoneNumber(entities.MaltegoEntity):
	"""
	A telephone number
	"""

	id = 'maltego.PhoneNumber'
	displayName = 'Phone Number'
	displayNamePlural = 'Phone Numbers'

	phonenumber = None # string phonenumber
	phonenumber_countrycode = None # string phonenumber.countrycode
	phonenumber_citycode = None # string phonenumber.citycode
	phonenumber_areacode = None # string phonenumber.areacode
	phonenumber_lastnumbers = None # string phonenumber.lastnumbers

	_fields = {
		'phonenumber': {'name': 'phonenumber', 'type': 'string', 'nullable': 'true'},
		'phonenumber_countrycode': {'name': 'phonenumber.countrycode', 'type': 'string', 'nullable': 'true'},
		'phonenumber_citycode': {'name': 'phonenumber.citycode', 'type': 'string', 'nullable': 'true'},
		'phonenumber_areacode': {'name': 'phonenumber.areacode', 'type': 'string', 'nullable': 'true'},
		'phonenumber_lastnumbers': {'name': 'phonenumber.lastnumbers', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, phonenumber=None, phonenumber_countrycode=None, phonenumber_citycode=None, phonenumber_areacode=None, phonenumber_lastnumbers=None, **kwargs):
		super().__init__(value, **kwargs)
		self.phonenumber = phonenumber
		self.phonenumber_countrycode = phonenumber_countrycode
		self.phonenumber_citycode = phonenumber_citycode
		self.phonenumber_areacode = phonenumber_areacode
		self.phonenumber_lastnumbers = phonenumber_lastnumbers

entities.entity_map[PhoneNumber.id] = PhoneNumber
