# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Personal" conversionOrder="10000" description="Any text or part thereof" displayName="Phrase" displayNamePlural="Phrases" id="maltego.Phrase" largeIconResource="Phrase" smallIconResource="Phrase" visible="true">
	   <Converter>
	      <Value>.*</Value>
	   </Converter>
	   <Properties displayValue="text" value="text">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="Text" hidden="false" name="text" nullable="true" readonly="false" type="string">
	            <SampleValue>Some phrase</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Phrase(entities.MaltegoEntity):
	"""
	Any text or part thereof
	"""

	id = 'maltego.Phrase'
	displayName = 'Phrase'
	displayNamePlural = 'Phrases'

	text = None # string text

	_fields = {
		'text': {'name': 'text', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, text=None, **kwargs):
		super().__init__(value, **kwargs)
		self.text = text

entities.entity_map[Phrase.id] = Phrase
