# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Locations" conversionOrder="2147483647" description="A building to which people are legally committed as a punishment for crimes they have committed or while awaiting trial" displayName="Prison" displayNamePlural="Prisons" id="maltego.Prison" largeIconResource="Prison" smallIconResource="Prison" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Location</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields>
	         <Field description="" displayName="Name" hidden="false" name="location.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Alcatraz</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Location import Location

class Prison(Location):
	"""
	A building to which people are legally committed as a punishment for crimes they have committed or while awaiting trial
	"""

	id = 'maltego.Prison'
	displayName = 'Prison'
	displayNamePlural = 'Prisons'

	location_name = None # string location.name

	_fields = {
		'location_name': {'name': 'location.name', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, location_name=None, **kwargs):
		super().__init__(value, **kwargs)
		self.location_name = location_name

entities.entity_map[Prison.id] = Prison
