# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Groups" conversionOrder="2147483647" description="A group of people who share religious or spiritual beliefs" displayName="Religious Group" displayNamePlural="Religious Groups" id="maltego.ReligiousGroup" largeIconResource="Church" smallIconResource="Church" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Organization</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="Name of the religious group" displayName="Name" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Pastafarians</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Organization import Organization

class ReligiousGroup(Organization):
	"""
	A group of people who share religious or spiritual beliefs
	"""

	id = 'maltego.ReligiousGroup'
	displayName = 'Religious Group'
	displayNamePlural = 'Religious Groups'

	title = None # string title

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title

entities.entity_map[ReligiousGroup.id] = ReligiousGroup
