# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="Section name or hash" displayName="Section" displayNamePlural="Sections" id="maltego.Section" largeIconResource="MedicalRecord" smallIconResource="MedicalRecord" visible="true">
	   <Properties displayValue="properties.section" value="properties.section">
	      <Fields>
	         <Field description="" displayName="Section" hidden="false" name="properties.section" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Section(entities.MaltegoEntity):
	"""
	Section name or hash
	"""

	id = 'maltego.Section'
	displayName = 'Section'
	displayNamePlural = 'Sections'

	properties_section = None # string properties.section

	_fields = {
		'properties_section': {'name': 'properties.section', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_section=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_section = properties_section

entities.entity_map[Section.id] = Section
