# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Personal" conversionOrder="2147483647" description="This represent the sentiment towards an entity." displayName="Sentiment" displayNamePlural="Sentiments" id="maltego.Sentiment" largeIconResource="Smile" smallIconResource="Smile" visible="true">
	   <Properties displayValue="properties.sentiment" value="properties.sentiment">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="Sentiment" hidden="false" name="properties.sentiment" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>Positive</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Sentiment(entities.MaltegoEntity):
	"""
	This represent the sentiment towards an entity.
	"""

	id = 'maltego.Sentiment'
	displayName = 'Sentiment'
	displayNamePlural = 'Sentiments'

	properties_sentiment = None # string properties.sentiment

	_fields = {
		'properties_sentiment': {'name': 'properties.sentiment', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_sentiment=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_sentiment = properties_sentiment

entities.entity_map[Sentiment.id] = Sentiment
