# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Penetration Testing" conversionOrder="2147483647" description="Network service (port and banner combination)" displayName="Service" displayNamePlural="Services" id="maltego.Service" largeIconResource="Service" smallIconResource="Service" visible="true">
	   <Properties displayValue="service.name" value="service.name">
	      <Fields>
	         <Field description="" displayName="Description" hidden="false" name="service.name" nullable="true" readonly="false" type="string">
	            <DefaultValue>80/Apache 9</DefaultValue>
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Port" hidden="false" name="port.number" nullable="true" readonly="false" type="int">
	            <DefaultValue>80</DefaultValue>
	            <SampleValue>0</SampleValue>
	         </Field>
	         <Field description="" displayName="Service banner" hidden="false" name="banner.text" nullable="true" readonly="false" type="string">
	            <DefaultValue>Apache 9</DefaultValue>
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Service" hidden="false" name="properties.service" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>80:Apache</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Service(entities.MaltegoEntity):
	"""
	Network service (port and banner combination)
	"""

	id = 'maltego.Service'
	displayName = 'Service'
	displayNamePlural = 'Services'

	service_name = None # string service.name
	port_number = None # int port.number
	banner_text = None # string banner.text
	properties_service = None # string properties.service

	_fields = {
		'service_name': {'name': 'service.name', 'type': 'string', 'nullable': 'true'},
		'port_number': {'name': 'port.number', 'type': 'int', 'nullable': 'true'},
		'banner_text': {'name': 'banner.text', 'type': 'string', 'nullable': 'true'},
		'properties_service': {'name': 'properties.service', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, service_name=None, port_number=None, banner_text=None, properties_service=None, **kwargs):
		super().__init__(value, **kwargs)
		self.service_name = service_name
		self.port_number = port_number
		self.banner_text = banner_text
		self.properties_service = properties_service

entities.entity_map[Service.id] = Service
