# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="Someone who has been convicted of a sex crime" displayName="Sex Offender" displayNamePlural="Sex Offenders" id="maltego.SexOffender" largeIconResource="SexOffender" smallIconResource="SexOffender" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.BadGuy</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.BadGuy import BadGuy

class SexOffender(BadGuy):
	"""
	Someone who has been convicted of a sex crime
	"""

	id = 'maltego.SexOffender'
	displayName = 'Sex Offender'
	displayNamePlural = 'Sex Offenders'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[SexOffender.id] = SexOffender
