# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Devices" conversionOrder="2147483647" description="A mobile phone that offers more advanced computing ability and connectivity" displayName="Smartphone" displayNamePlural="Smartphones" id="maltego.Smartphone" largeIconResource="Smartphone" smallIconResource="Smartphone" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.MobilePhone</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="device" value="device">
	      <Fields>
	         <Field description="device" displayName="Device" hidden="false" name="device" nullable="true" readonly="false" type="string">
	            <SampleValue>HTC</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.MobilePhone import MobilePhone

class Smartphone(MobilePhone):
	"""
	A mobile phone that offers more advanced computing ability and connectivity
	"""

	id = 'maltego.Smartphone'
	displayName = 'Smartphone'
	displayNamePlural = 'Smartphones'

	device = None # string device

	_fields = {
		'device': {'name': 'device', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, device=None, **kwargs):
		super().__init__(value, **kwargs)
		self.device = device

entities.entity_map[Smartphone.id] = Smartphone
