# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="People" conversionOrder="2147483647" description="A leader of a terrorist group" displayName="Terrorist Leader" displayNamePlural="Terrorist Leaders" id="maltego.TerroristLeader" largeIconResource="TerroristLeader" smallIconResource="TerroristLeader" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Terrorist</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields />
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Terrorist import Terrorist

class TerroristLeader(Terrorist):
	"""
	A leader of a terrorist group
	"""

	id = 'maltego.TerroristLeader'
	displayName = 'Terrorist Leader'
	displayNamePlural = 'Terrorist Leaders'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)

entities.entity_map[TerroristLeader.id] = TerroristLeader
