# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="Timestamp" displayName="Timestamp" displayNamePlural="Timestamps" id="maltego.Timestamp" largeIconResource="Clock" smallIconResource="Clock" visible="true">
	   <Properties displayValue="properties.timestamp" value="properties.timestamp">
	      <Fields>
	         <Field description="" displayName="Timestamp" hidden="false" name="properties.timestamp" nullable="true" readonly="false" type="string">
	            <SampleValue>2011:02:02 19:55:02+01:00</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Timestamp(entities.MaltegoEntity):
	"""
	Timestamp
	"""

	id = 'maltego.Timestamp'
	displayName = 'Timestamp'
	displayNamePlural = 'Timestamps'

	properties_timestamp = None # string properties.timestamp

	_fields = {
		'properties_timestamp': {'name': 'properties.timestamp', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_timestamp=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_timestamp = properties_timestamp

entities.entity_map[Timestamp.id] = Timestamp
