# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Locations" conversionOrder="2147483647" description="A place where passengers and cargo are exchanged between vehicles" displayName="Transport Hub" displayNamePlural="Transport Hubs" id="maltego.TransportHub" largeIconResource="TrainStation" smallIconResource="TrainStation" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Location</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields>
	         <Field description="" displayName="Name" hidden="false" name="location.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Transport Hub</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Location import Location

class TransportHub(Location):
	"""
	A place where passengers and cargo are exchanged between vehicles
	"""

	id = 'maltego.TransportHub'
	displayName = 'Transport Hub'
	displayNamePlural = 'Transport Hubs'

	location_name = None # string location.name

	_fields = {
		'location_name': {'name': 'location.name', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, location_name=None, **kwargs):
		super().__init__(value, **kwargs)
		self.location_name = location_name

entities.entity_map[TransportHub.id] = TransportHub
