# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Social Network" conversionOrder="2147483647" description="Twitter User List entity" displayName="Twitter User List" displayNamePlural="Twitter User Lists" id="maltego.TwitterUserList" largeIconResource="Twitter" smallIconResource="Twitter" visible="true">
	   <Properties displayValue="twitter.list.name" value="twitter.list.name">
	      <Fields>
	         <Field description="" displayName="Name" hidden="false" name="twitter.list.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Staff</SampleValue>
	         </Field>
	         <Field description="" displayName="Full Name" hidden="false" name="twitter.list.fullname" nullable="true" readonly="false" type="string">
	            <SampleValue>@Paterva/staff</SampleValue>
	         </Field>
	         <Field description="" displayName="ID" hidden="false" name="twitter.list.id" nullable="true" readonly="false" type="string">
	            <SampleValue>211220868</SampleValue>
	         </Field>
	         <Field description="" displayName="Description" hidden="false" name="twitter.list.description" nullable="true" readonly="false" type="string">
	            <SampleValue>Direct Paterva staff.</SampleValue>
	         </Field>
	         <Field description="" displayName="Member Count" hidden="false" name="twitter.list.members" nullable="true" readonly="false" type="int">
	            <SampleValue>3</SampleValue>
	         </Field>
	         <Field description="" displayName="Subscriber Count" hidden="false" name="twitter.list.subscribers" nullable="true" readonly="false" type="int">
	            <SampleValue>0</SampleValue>
	         </Field>
	         <Field description="" displayName="Slug" hidden="false" name="twitter.list.slug" nullable="true" readonly="false" type="string">
	            <SampleValue>staff</SampleValue>
	         </Field>
	         <Field description="" displayName="URI" hidden="false" name="twitter.list.uri" nullable="true" readonly="false" type="string">
	            <SampleValue>/Paterva/lists/staff</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class TwitterUserList(entities.MaltegoEntity):
	"""
	Twitter User List entity
	"""

	id = 'maltego.TwitterUserList'
	displayName = 'Twitter User List'
	displayNamePlural = 'Twitter User Lists'

	twitter_list_name = None # string twitter.list.name
	twitter_list_fullname = None # string twitter.list.fullname
	twitter_list_id = None # string twitter.list.id
	twitter_list_description = None # string twitter.list.description
	twitter_list_members = None # int twitter.list.members
	twitter_list_subscribers = None # int twitter.list.subscribers
	twitter_list_slug = None # string twitter.list.slug
	twitter_list_uri = None # string twitter.list.uri

	_fields = {
		'twitter_list_name': {'name': 'twitter.list.name', 'type': 'string', 'nullable': 'true'},
		'twitter_list_fullname': {'name': 'twitter.list.fullname', 'type': 'string', 'nullable': 'true'},
		'twitter_list_id': {'name': 'twitter.list.id', 'type': 'string', 'nullable': 'true'},
		'twitter_list_description': {'name': 'twitter.list.description', 'type': 'string', 'nullable': 'true'},
		'twitter_list_members': {'name': 'twitter.list.members', 'type': 'int', 'nullable': 'true'},
		'twitter_list_subscribers': {'name': 'twitter.list.subscribers', 'type': 'int', 'nullable': 'true'},
		'twitter_list_slug': {'name': 'twitter.list.slug', 'type': 'string', 'nullable': 'true'},
		'twitter_list_uri': {'name': 'twitter.list.uri', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, twitter_list_name=None, twitter_list_fullname=None, twitter_list_id=None, twitter_list_description=None, twitter_list_members=None, twitter_list_subscribers=None, twitter_list_slug=None, twitter_list_uri=None, **kwargs):
		super().__init__(value, **kwargs)
		self.twitter_list_name = twitter_list_name
		self.twitter_list_fullname = twitter_list_fullname
		self.twitter_list_id = twitter_list_id
		self.twitter_list_description = twitter_list_description
		self.twitter_list_members = twitter_list_members
		self.twitter_list_subscribers = twitter_list_subscribers
		self.twitter_list_slug = twitter_list_slug
		self.twitter_list_uri = twitter_list_uri

entities.entity_map[TwitterUserList.id] = TwitterUserList
