# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Social Network" conversionOrder="2147483647" description="Tweet entity" displayName="Tweet" displayNamePlural="Tweets" id="maltego.Twit" largeIconResource="Twitter" smallIconResource="Twitter" visible="true">
	   <Properties displayValue="twit.name" value="twit.name">
	      <Fields>
	         <Field description="" displayName="Tweet" hidden="false" name="twit.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Over 10,000 Maltego Community Edition users!</SampleValue>
	         </Field>
	         <Field description="" displayName="Tweet ID" hidden="false" name="id" nullable="true" readonly="false" type="string">
	            <SampleValue>tag:search.twitter.com,2005:27916568578</SampleValue>
	         </Field>
	         <Field description="" displayName="Author" hidden="false" name="author" nullable="true" readonly="false" type="string">
	            <SampleValue>Paterva (Paterva)</SampleValue>
	         </Field>
	         <Field description="" displayName="Author URI" hidden="false" name="author_uri" nullable="true" readonly="false" type="string">
	            <SampleValue>http://twitter.com/Paterva</SampleValue>
	         </Field>
	         <Field description="" displayName="Content" hidden="false" name="content" nullable="true" readonly="false" type="string">
	            <SampleValue>Over 10,000 Maltego Community Edition users!</SampleValue>
	         </Field>
	         <Field description="" displayName="Image Link" hidden="false" name="imglink" nullable="true" readonly="false" type="string">
	            <SampleValue>http://a3.twimg.com/profile_images/355901931/patervatwitter_normal.png</SampleValue>
	         </Field>
	         <Field description="" displayName="Date published" hidden="false" name="pubdate" nullable="true" readonly="false" type="string">
	            <SampleValue>2010-10-20T09:54:01Z</SampleValue>
	         </Field>
	         <Field description="" displayName="Title" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Over 10,000 Maltego Community Edition users!</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Twit(entities.MaltegoEntity):
	"""
	Tweet entity
	"""

	id = 'maltego.Twit'
	displayName = 'Tweet'
	displayNamePlural = 'Tweets'

	twit_name = None # string twit.name
	id = None # string id
	author = None # string author
	author_uri = None # string author_uri
	content = None # string content
	imglink = None # string imglink
	pubdate = None # string pubdate
	title = None # string title

	_fields = {
		'twit_name': {'name': 'twit.name', 'type': 'string', 'nullable': 'true'},
		'id': {'name': 'id', 'type': 'string', 'nullable': 'true'},
		'author': {'name': 'author', 'type': 'string', 'nullable': 'true'},
		'author_uri': {'name': 'author_uri', 'type': 'string', 'nullable': 'true'},
		'content': {'name': 'content', 'type': 'string', 'nullable': 'true'},
		'imglink': {'name': 'imglink', 'type': 'string', 'nullable': 'true'},
		'pubdate': {'name': 'pubdate', 'type': 'string', 'nullable': 'true'},
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, twit_name=None, id=None, author=None, author_uri=None, content=None, imglink=None, pubdate=None, title=None, **kwargs):
		super().__init__(value, **kwargs)
		self.twit_name = twit_name
		self.id = id
		self.author = author
		self.author_uri = author_uri
		self.content = content
		self.imglink = imglink
		self.pubdate = pubdate
		self.title = title

entities.entity_map[Twit.id] = Twit
