# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="2147483647" description="Represents a tracking code for a web service." displayName="Tracking Code" displayNamePlural="UniqueIdentifiers" id="maltego.UniqueIdentifier" largeIconResource="LogGolden" smallIconResource="LogGolden" visible="true">
	   <Properties displayValue="properties.uniqueidentifier" value="properties.uniqueidentifier">
	      <Groups />
	      <Fields>
	         <Field description="" displayName="UniqueIdentifier" hidden="false" name="properties.uniqueidentifier" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>UA-1553321-*</SampleValue>
	         </Field>
	         <Field description="" displayName="Identifier Type" hidden="false" name="identifierType" nullable="true" readonly="false" type="string">
	            <SampleValue>Google Analytics ID</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class UniqueIdentifier(entities.MaltegoEntity):
	"""
	Represents a tracking code for a web service.
	"""

	id = 'maltego.UniqueIdentifier'
	displayName = 'Tracking Code'
	displayNamePlural = 'UniqueIdentifiers'

	properties_uniqueidentifier = None # string properties.uniqueidentifier
	identifiertype = None # string identifierType

	_fields = {
		'properties_uniqueidentifier': {'name': 'properties.uniqueidentifier', 'type': 'string', 'nullable': 'true'},
		'identifiertype': {'name': 'identifierType', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_uniqueidentifier=None, identifiertype=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_uniqueidentifier = properties_uniqueidentifier
		self.identifiertype = identifiertype

entities.entity_map[UniqueIdentifier.id] = UniqueIdentifier
