# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" conversionOrder="2147483647" description="An entity of unknown type" displayName="Unknown" displayNamePlural="Unknowns" id="maltego.Unknown" largeIconResource="Unknown" visible="false">
	   <Actions>
	      <Action displayName="Google Me!" name="maltego.spec.action.google" type="maltego.spec.action.type.browser">
	         <Config>http://www.google.com/search?q=$urlencode("$value()")</Config>
	      </Action>
	      <Action displayName="Wikipedia Me!" name="maltego.spec.action.wikipedia" type="maltego.spec.action.type.browser">
	         <Config>http://en.wikipedia.org/wiki/Special:Search?search=$urlencode("$value()")</Config>
	      </Action>
	      <Action displayName="Open all URLs" name="maltego.spec.action.browse-urls" type="maltego.spec.action.type.browse-urls" />
	   </Actions>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Unknown(entities.MaltegoEntity):
	"""
	An entity of unknown type
	"""

	id = 'maltego.Unknown'
	displayName = 'Unknown'
	displayNamePlural = 'Unknowns'


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)
