# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" description="A filter that pops up a dialog and lets the user filter results" displayName="User Filter" id="maltego.UserFilterAction" largeIconResource="QuestionDialog" visible="false">
	   <BaseEntities>
	      <BaseEntity>maltego.FilterAction</BaseEntity>
	   </BaseEntities>
	</MaltegoEntity>

"""

from tedious.entities.maltego.FilterAction import FilterAction

class UserFilterAction(FilterAction):
	"""
	A filter that pops up a dialog and lets the user filter results
	"""

	id = 'maltego.UserFilterAction'
	displayName = 'User Filter'
	displayNamePlural = None


	_fields = {
	}

	def __init__(self, value, **kwargs):
		super().__init__(value, **kwargs)
