# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Malware" conversionOrder="2147483647" description="User-Agent" displayName="User-Agent" displayNamePlural="User-Agents" id="maltego.Useragent" largeIconResource="Leader" smallIconResource="Leader" visible="true">
	   <Properties displayValue="properties.user-agent" value="properties.user-agent">
	      <Fields>
	         <Field description="" displayName="User-Agent" hidden="false" name="properties.user-agent" nullable="true" readonly="false" type="string">
	            <DefaultValue> </DefaultValue>
	            <SampleValue>-</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Useragent(entities.MaltegoEntity):
	"""
	User-Agent
	"""

	id = 'maltego.Useragent'
	displayName = 'User-Agent'
	displayNamePlural = 'User-Agents'

	properties_user_agent = None # string properties.user-agent

	_fields = {
		'properties_user_agent': {'name': 'properties.user-agent', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, properties_user_agent=None, **kwargs):
		super().__init__(value, **kwargs)
		self.properties_user_agent = properties_user_agent

entities.entity_map[Useragent.id] = Useragent
