# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Tracking" conversionOrder="2147483647" description="The registration or license number usually mounted on a vehicle for identification" displayName="Vehicle Registration" displayNamePlural="Vehicle Registrations" id="maltego.VehicleRegistration" largeIconResource="RegistrationPlate" smallIconResource="RegistrationPlate" visible="true">
	   <Properties displayValue="vehicle.registration" value="vehicle.registration">
	      <Fields>
	         <Field description="A vehicle registration or license number" displayName="Registration Number" hidden="false" name="vehicle.registration" nullable="true" readonly="false" type="string">
	            <SampleValue>BCA555GP</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class VehicleRegistration(entities.MaltegoEntity):
	"""
	The registration or license number usually mounted on a vehicle for identification
	"""

	id = 'maltego.VehicleRegistration'
	displayName = 'Vehicle Registration'
	displayNamePlural = 'Vehicle Registrations'

	vehicle_registration = None # string vehicle.registration

	_fields = {
		'vehicle_registration': {'name': 'vehicle.registration', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, vehicle_registration=None, **kwargs):
		super().__init__(value, **kwargs)
		self.vehicle_registration = vehicle_registration

entities.entity_map[VehicleRegistration.id] = VehicleRegistration
