# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Tracking" conversionOrder="2147483647" description="A Vehicle Identification Number" displayName="VIN Number" displayNamePlural="VIN Numbers" id="maltego.VinNumber" largeIconResource="VinNumber" smallIconResource="VinNumber" visible="true">
	   <Properties displayValue="vinnumber" value="vinnumber">
	      <Fields>
	         <Field description="Vehicle Identification Number" displayName="VIN Number" hidden="false" name="vinnumber" nullable="true" readonly="false" type="string">
	            <SampleValue>5GZCZ43D13S812715</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class VinNumber(entities.MaltegoEntity):
	"""
	A Vehicle Identification Number
	"""

	id = 'maltego.VinNumber'
	displayName = 'VIN Number'
	displayNamePlural = 'VIN Numbers'

	vinnumber = None # string vinnumber

	_fields = {
		'vinnumber': {'name': 'vinnumber', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, vinnumber=None, **kwargs):
		super().__init__(value, **kwargs)
		self.vinnumber = vinnumber

entities.entity_map[VinNumber.id] = VinNumber
