# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Weapons" conversionOrder="2147483647" description="Something used for inflicting bodily harm or physical damage" displayName="Weapon" displayNamePlural="Weapons" id="maltego.Weapon" largeIconResource="Gun" smallIconResource="Gun" visible="true">
	   <Properties displayValue="weapon.type" value="weapon.type">
	      <Fields>
	         <Field description="Weapon type" displayName="Type" hidden="false" name="weapon.type" nullable="true" readonly="false" type="string">
	            <SampleValue>Weapon</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class Weapon(entities.MaltegoEntity):
	"""
	Something used for inflicting bodily harm or physical damage
	"""

	id = 'maltego.Weapon'
	displayName = 'Weapon'
	displayNamePlural = 'Weapons'

	weapon_type = None # string weapon.type

	_fields = {
		'weapon_type': {'name': 'weapon.type', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, weapon_type=None, **kwargs):
		super().__init__(value, **kwargs)
		self.weapon_type = weapon_type

entities.entity_map[Weapon.id] = Weapon
