# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Infrastructure" conversionOrder="100" description="An internet website" displayName="Website" displayNamePlural="Websites" id="maltego.Website" largeIconResource="Website" smallIconResource="Website" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.DNSName</BaseEntity>
	   </BaseEntities>
	   <Converter>
	      <Value>(http://|https://)[-\w\.\:]*/*</Value>
	   </Converter>
	   <Properties displayValue="fqdn" value="fqdn">
	      <Fields>
	         <Field description="" displayName="Website" hidden="false" name="fqdn" nullable="true" readonly="false" type="string">
	            <SampleValue>www.paterva.com</SampleValue>
	         </Field>
	         <Field description="" displayName="SSL Enabled" hidden="false" name="website.ssl-enabled" nullable="true" readonly="false" type="boolean">
	            <SampleValue>false</SampleValue>
	         </Field>
	         <Field description="" displayName="Ports" hidden="false" name="ports" nullable="true" readonly="false" type="int[]">
	            <DefaultValue>80</DefaultValue>
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	   <Overlays>
	      <Overlay position="SW" propertyName="$property(fqdn)/favicon.ico" type="image" />
	   </Overlays>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.DNSName import DNSName

class Website(DNSName):
	"""
	An internet website
	"""

	id = 'maltego.Website'
	displayName = 'Website'
	displayNamePlural = 'Websites'

	fqdn = None # string fqdn
	website_ssl_enabled = None # boolean website.ssl-enabled
	ports = None # int[] ports

	_fields = {
		'fqdn': {'name': 'fqdn', 'type': 'string', 'nullable': 'true'},
		'website_ssl_enabled': {'name': 'website.ssl-enabled', 'type': 'boolean', 'nullable': 'true'},
		'ports': {'name': 'ports', 'type': 'int[]', 'nullable': 'true'},
	}

	def __init__(self, value, fqdn=None, website_ssl_enabled=None, ports=None, **kwargs):
		super().__init__(value, **kwargs)
		self.fqdn = fqdn
		self.website_ssl_enabled = website_ssl_enabled
		self.ports = ports

entities.entity_map[Website.id] = Website
