# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Infrastructure" conversionOrder="2147483647" description="Title of a website" displayName="Website Title" displayNamePlural="Website Titles" id="maltego.WebTitle" largeIconResource="Alarm" smallIconResource="Alarm" visible="true">
	   <Properties displayValue="title" value="title">
	      <Fields>
	         <Field description="" displayName="Title" hidden="false" name="title" nullable="true" readonly="false" type="string">
	            <SampleValue>Paterva (Pty) Ltd</SampleValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities

class WebTitle(entities.MaltegoEntity):
	"""
	Title of a website
	"""

	id = 'maltego.WebTitle'
	displayName = 'Website Title'
	displayNamePlural = 'Website Titles'

	title = None # string title

	_fields = {
		'title': {'name': 'title', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, title=None, **kwargs):
		super().__init__(value, **kwargs)
		self.title = title

entities.entity_map[WebTitle.id] = WebTitle
