# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Social Network" conversionOrder="2147483647" description="Membership of the Flickr social network" displayName="Affiliation - Flickr" displayNamePlural="Affiliations - Flickr" id="maltego.affiliation.Flickr" largeIconResource="Flickr" smallIconResource="Flickr" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Affiliation</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="">
	      <Fields>
	         <Field description="" displayName="Network" hidden="false" name="affiliation.network" nullable="true" readonly="true" type="string">
	            <DefaultValue>Flickr</DefaultValue>
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Affiliation import Affiliation

class Flickr(Affiliation):
	"""
	Membership of the Flickr social network
	"""

	id = 'maltego.affiliation.Flickr'
	displayName = 'Affiliation - Flickr'
	displayNamePlural = 'Affiliations - Flickr'

	affiliation_network = None # string affiliation.network

	_fields = {
		'affiliation_network': {'name': 'affiliation.network', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, affiliation_network=None, **kwargs):
		super().__init__(value, **kwargs)
		self.affiliation_network = affiliation_network

entities.entity_map[Flickr.id] = Flickr
