# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="true" category="Social Network" conversionOrder="2147483647" description="Membership of the LinkedIn business network" displayName="Affiliation - LinkedIn" displayNamePlural="Affiliations - LinkedIn" id="maltego.affiliation.LinkedIn" largeIconResource="LinkedIn" smallIconResource="LinkedIn" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Affiliation</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="person.name" value="person.name">
	      <Fields>
	         <Field description="" displayName="Name" hidden="false" name="person.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Name Surname</SampleValue>
	         </Field>
	         <Field description="" displayName="Network" hidden="false" name="affiliation.network" nullable="true" readonly="true" type="string">
	            <DefaultValue>LinkedIn</DefaultValue>
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Affiliation import Affiliation

class LinkedIn(Affiliation):
	"""
	Membership of the LinkedIn business network
	"""

	id = 'maltego.affiliation.LinkedIn'
	displayName = 'Affiliation - LinkedIn'
	displayNamePlural = 'Affiliations - LinkedIn'

	person_name = None # string person.name
	affiliation_network = None # string affiliation.network

	_fields = {
		'person_name': {'name': 'person.name', 'type': 'string', 'nullable': 'true'},
		'affiliation_network': {'name': 'affiliation.network', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, person_name=None, affiliation_network=None, **kwargs):
		super().__init__(value, **kwargs)
		self.person_name = person_name
		self.affiliation_network = affiliation_network

entities.entity_map[LinkedIn.id] = LinkedIn
