# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" conversionOrder="2147483647" description="A social network membership tracked by Spock" displayName="Affiliation - Spock" displayNamePlural="Affiliations - Spock" id="maltego.affiliation.Spock" largeIconResource="Spock">
	   <BaseEntities>
	      <BaseEntity>maltego.Affiliation</BaseEntity>
	   </BaseEntities>
	   <Properties>
	      <Fields>
	         <Field displayName="Network" hidden="false" name="affiliation.network" nullable="true" readonly="true" type="string">
	            <DefaultValue>Spock</DefaultValue>
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

from tedious.entities.maltego.Affiliation import Affiliation

class Spock(Affiliation):
	"""
	A social network membership tracked by Spock
	"""

	id = 'maltego.affiliation.Spock'
	displayName = 'Affiliation - Spock'
	displayNamePlural = 'Affiliations - Spock'

	affiliation_network = None # string affiliation.network

	_fields = {
		'affiliation_network': {'name': 'affiliation.network', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, affiliation_network=None, **kwargs):
		super().__init__(value, **kwargs)
		self.affiliation_network = affiliation_network
