# The contents of this file have been autogenerated. Edit at your own risk!!!
# Despite this, it *is* intended to be human readable.

"""
.. highlight:: xml
.. code-block:: xml

	<MaltegoEntity allowedRoot="false" category="Social Network" conversionOrder="2147483647" description="Membership of Twitter" displayName="Affiliation - Twitter" displayNamePlural="Affiliations - Twitter" id="maltego.affiliation.Twitter" largeIconResource="Twitter" smallIconResource="Twitter" visible="true">
	   <BaseEntities>
	      <BaseEntity>maltego.Affiliation</BaseEntity>
	   </BaseEntities>
	   <Properties displayValue="person.name" value="person.name">
	      <Fields>
	         <Field description="" displayName="Name" hidden="false" name="person.name" nullable="true" readonly="false" type="string">
	            <SampleValue>Paterva</SampleValue>
	         </Field>
	         <Field description="" displayName="Network" hidden="false" name="affiliation.network" nullable="true" readonly="true" type="string">
	            <DefaultValue>Twitter</DefaultValue>
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="UID" hidden="false" name="affiliation.uid" nullable="true" readonly="false" type="string">
	            <SampleValue>Paterva</SampleValue>
	         </Field>
	         <Field description="" displayName="Profile URL" hidden="false" name="affiliation.profile-url" nullable="true" readonly="false" type="string">
	            <SampleValue>http://twitter.com/Paterva</SampleValue>
	         </Field>
	         <Field description="" displayName="Twitter ID" hidden="false" name="twitter.id" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Screen Name" hidden="false" name="twitter.screen-name" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	         <Field description="" displayName="Friend Count" hidden="false" name="twitter.friendcount" nullable="true" readonly="false" type="int">
	            <SampleValue>0</SampleValue>
	         </Field>
	         <Field description="" displayName="Real Name" hidden="false" name="person.fullname" nullable="true" readonly="false" type="string">
	            <SampleValue />
	         </Field>
	      </Fields>
	   </Properties>
	</MaltegoEntity>

"""

import tedious.entities as entities
from tedious.entities.maltego.Affiliation import Affiliation

class Twitter(Affiliation):
	"""
	Membership of Twitter
	"""

	id = 'maltego.affiliation.Twitter'
	displayName = 'Affiliation - Twitter'
	displayNamePlural = 'Affiliations - Twitter'

	person_name = None # string person.name
	affiliation_network = None # string affiliation.network
	affiliation_uid = None # string affiliation.uid
	affiliation_profile_url = None # string affiliation.profile-url
	twitter_id = None # string twitter.id
	twitter_screen_name = None # string twitter.screen-name
	twitter_friendcount = None # int twitter.friendcount
	person_fullname = None # string person.fullname

	_fields = {
		'person_name': {'name': 'person.name', 'type': 'string', 'nullable': 'true'},
		'affiliation_network': {'name': 'affiliation.network', 'type': 'string', 'nullable': 'true'},
		'affiliation_uid': {'name': 'affiliation.uid', 'type': 'string', 'nullable': 'true'},
		'affiliation_profile_url': {'name': 'affiliation.profile-url', 'type': 'string', 'nullable': 'true'},
		'twitter_id': {'name': 'twitter.id', 'type': 'string', 'nullable': 'true'},
		'twitter_screen_name': {'name': 'twitter.screen-name', 'type': 'string', 'nullable': 'true'},
		'twitter_friendcount': {'name': 'twitter.friendcount', 'type': 'int', 'nullable': 'true'},
		'person_fullname': {'name': 'person.fullname', 'type': 'string', 'nullable': 'true'},
	}

	def __init__(self, value, person_name=None, affiliation_network=None, affiliation_uid=None, affiliation_profile_url=None, twitter_id=None, twitter_screen_name=None, twitter_friendcount=None, person_fullname=None, **kwargs):
		super().__init__(value, **kwargs)
		self.person_name = person_name
		self.affiliation_network = affiliation_network
		self.affiliation_uid = affiliation_uid
		self.affiliation_profile_url = affiliation_profile_url
		self.twitter_id = twitter_id
		self.twitter_screen_name = twitter_screen_name
		self.twitter_friendcount = twitter_friendcount
		self.person_fullname = person_fullname

entities.entity_map[Twitter.id] = Twitter
